name: GroupMe Automated Message

on:
  schedule:
    - cron: '0 8 * * *' # This sends the message every single day at 12:00 PM UTC (6:00) AM EST)

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Post Request to GroupMe
        run: |
          curl -X POST https://groupme.com \
          -H "Content-Type: application/json" \
          -d '{"bot_id": "Pa483170944e3a23de1e60df749", "text": "Test testing edited"}'
